export type Book = {
    id: number,
    title: string,
    author: string,
    read: boolean,
}

export const dummyData: Book[] = [
    { id: 1, title: "The Silent Path", author: "Ava Storm", read: true },
    { id: 2, title: "Echoes of Dust", author: "Liam Hart", read: false },
    { id: 3, title: "Whispers in Code", author: "Nora Byte", read: true },
    { id: 4, title: "The Last Horizon", author: "Zane Frost", read: false },
    { id: 5, title: "Fragments of Time", author: "Mira Voss", read: true },
    { id: 6, title: "Steel and Silence", author: "Calen Dusk", read: false },
    { id: 7, title: "Midnight Algorithms", author: "Rhea Sparks", read: true },
    { id: 8, title: "Dreamcatcher Protocol", author: "Dane Vex", read: false },
    { id: 9, title: "Shadows of Babel", author: "Talia Knox", read: true },
    { id: 10, title: "Parallel Lines", author: "Eli Shore", read: true },
    { id: 11, title: "Fire Between Worlds", author: "Lana Mirth", read: false },
    { id: 12, title: "Circuit Heart", author: "Axel Rowe", read: true },
    { id: 13, title: "Gravity’s Echo", author: "Selene Moon", read: true },
    { id: 14, title: "The Memory Architect", author: "Orin Vale", read: false },
    { id: 15, title: "Glitch in the Light", author: "Nova Reed", read: true },
    { id: 16, title: "The Drowned Star", author: "Finn Calder", read: false },
    { id: 17, title: "Reflections of Steel", author: "Ivy Mare", read: true },
    { id: 18, title: "Cloud Diver", author: "Theo Lynx", read: false },
    { id: 19, title: "Riftwalker", author: "Zara Flint", read: true },
    { id: 20, title: "The Lost Syntax", author: "Juno Black", read: false },
    { id: 21, title: "The Quantum Thread", author: "Nico Venn", read: true },
    { id: 22, title: "Pulse of the Sky", author: "Tess Ember", read: false },
    { id: 23, title: "Neon Dreams", author: "Kai Vesper", read: true },
    { id: 24, title: "Silent Reboot", author: "Ira Haze", read: false },
    { id: 25, title: "Lightless Code", author: "Vera Locke", read: true },
    { id: 26, title: "Chrono Bloom", author: "Reed Solis", read: false },
    { id: 27, title: "Dust Circuit", author: "Owen Vale", read: true },
    { id: 28, title: "Sky Burned Blue", author: "Lyra Crest", read: true },
    { id: 29, title: "Zero in Bloom", author: "Milo Rune", read: false },
    { id: 30, title: "Ink Beyond Fire", author: "Clio Ash", read: true },
];
